Спринт 9: реализация стораджа, сервисов и контроллеров
sniskorodnova/java-filmorate pull request #2
Opened 2022-05-03 14:33 UTC by sniskorodnova

Реализация технического задания 9 спринта

2022-05-03 17:40 UTC, eugene-lenkevich requested changes
Привет, Света, спасибо за PR

В целом все супер :)
Есть совсем небольшие замечания, посмотри комментарии ниже, пожалуйста. Критичны только замечания про исключения, остальное на твое усмотрение =)

2022-05-03 17:40 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Тут, кстати, вроде как уже необязателен @Autowired
Вообще, вместо прописывания конструктора руками можно использовать аннотацию lombok @RequiredArgsConstructor :)

2022-05-03 17:40 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          log.info(film.toString());
Для распечатки данных лучше использовать уровень логирования ниже - то есть log.debug :)

2022-05-03 17:40 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Входящий запрос на удаление лайка пользователем с id = " + userId + " для фильма"
Тут можно использовать плейсхолдеры, даже лучше так как реальные расчеты могут быть отключены включением другого уровня логирования  :)

log.info("Входящий запрос на удаление лайка пользователем с id = {} для фильма с id = {}" , userId, filmId);

2022-05-03 17:40 UTC, eugene-lenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmNotFoundException.java
> +public class FilmNotFoundException extends RuntimeException {
То что фильм не найден - это штатная ситуация и ее надо обработать,  тут не стоит использовать непроверяемое исключение, которое означает возникновение какой то проблемы в самой логике приложения 
extends Exception :)

Ниже исключение - аналогично :)

2022-05-03 18:33 UTC, sniskorodnova commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Да, поправила это в обоих контроллерах:)

2022-05-03 18:41 UTC, sniskorodnova commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Входящий запрос на удаление лайка пользователем с id = " + userId + " для фильма"
Поменяла везде

2022-05-03 19:05 UTC, sniskorodnova commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          log.info(film.toString());
Поменяла

2022-05-04 07:09 UTC, sniskorodnova commented on src/main/java/ru/yandex/practicum/filmorate/exception/FilmNotFoundException.java
> +public class FilmNotFoundException extends RuntimeException {
Поправила

2022-05-04 07:28 UTC, sniskorodnova commented
Женя, спасибо за комментарии! Поправила все замечания

2022-05-04 07:47 UTC, eugene-lenkevich approved these changes
Все супер, спасибо!

2022-05-04 08:17 UTC, merged